version: '3.8'

services:
  mysql:
    image: mysql:8.1
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwop
      MYSQL_DATABASE: serverpro_db
      MYSQL_USER: user
      MYSQL_PASSWORD: qwop
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: