# Used to find player statistic files
default-world: "<worldname>"

# Message that is sent if player is not on the ground when using the /practice command.
block-message: "&3&l\u3010&b&lLinkCraft&3&l\u3011- &4You must be on a block to use the practice system!"

# Message that is sent to remind player that they are practicing.
practice-message: "&3&l\u3010&b&lLinkCraft&3&l\u3011- &aYou are on a practice mode, Do /unprac to stop."

# Message that is sent to the player when they finish practicing.
unpractice-message: "&3&l\u3010&b&lLinkCraft&3&l\u3011- &4You have stopped practicing."

# Message that is sent if the player uses /practice when they are already practicing
already-practicing-message: "&3&l\u3010&b&lLinkCraft&3&l\u3011- &4You are already in practice mode!"

# Message that is sent if the player uses /unpractice when they are not practicing.
not-practicing-message: "&3&l\u3010&b&lLinkCraft&3&l\u3011- &4You are not in a practice mode."

# Message that is sent if player has full inventory when using the /practice command.
full-inventory-message: "&3&l\u3010&b&lLinkCraft&3&l\u3011- &4Your inventory is full, Throw some items!"

# Message that is sent when a player uses /hideall
hide-all-msg: "&fYou are now &bhiding &fall players."

# Message that is sent when a player uses /hide
hide-one-msg: "&fYou are now &bhiding {player}"

# Message that is sent when a player uses /show
show-one-msg: "&fYou are now &bshowing {player}"

# Message that is sent when a player uses /showall
show-all-msg: "&fYou are now &bshowing &fall players."

# Message that is sent if a non player tries to execute a command
not-a-player: "&cYou have to be a player to execute this command."

# Message that is sent if a player executes a command that requires an online player, but they are offline
is-offline: "&c{player} is currently offline."

# ID:data of the return item. List of materials at https://helpch.at/docs/1.8/org/bukkit/Material.html
return-item-id: "SLIME_BALL:0"

# The name of the return item.
return-item-name: "&3&l\u3010&b&lLC&3&l\u3011-&4Return"

# For the next options, use [player] as a place holder for player name.
# Commands that are executed when a player makes a save. Use as a placeholder. (Send them to spawn)
save-commands:
  - mvtp [player] <worldname>

# Commands that are executed in the teleport animation when a player teleports to a save. (Its important to disable any signs)
save-teleport-commands:
  - pex user [player] add -serversigns.use.*
  - pex user [player] add -pk.signs
  - pex user [player] remove serversigns.use.*
  - pex user [player] remove pk.signs

# Commands that are executed when the teleport animation for saves is finished. (Enable permissions here)
save-teleport-finish-commands:
  - pex user [player] remove -serversigns.use.*
  - pex user [player] remove -pk.signs
  - pex user [player] add serversigns.use.*
  - pex user [player] add pk.signs

ggmessage: '&6&lG&e&lG'
glmessage: '&2&lG&a&lL'
ripmessage: '&0&lR&8&lI&f&lP'
hammessage: '&d&lha &c&lm'
eggsmessage: '&6&lE&e&lG&6&lg&e&LS'
failmessage: '&f&lFAIL'

# CHECKPOINTS
message-name: '&e« &4&lLink&c&lCraft &e»' # The name that shows up when messaging the player.
sign-name: '&5&lꕤ ꕤ ꕤ ꕤ ꕤ ꕤ ꕤ ꕤ' # The name that shows up on the sign.