name: LCCore
version: '${project.version}'
main: de.legoshi.lccore.Linkcraft
authors: [Leg0shi_, dklink750]
description: Practice Plugin for Linkcraft
api-version: 1.8
loadbefore:
  - Essentials
softdepend:
  - DiscordSRV
commands:
  ld:
    permission: lc.lockdown
  ldmsg:
    permission: lc.lockdownmsg
  practice:
    aliases: [prac]
    permission: pkprac.practice
  unpractice:
    aliases: [unprac]
    permission: pkprac.practice
  pkpracreload:
    permission: pkprac.reload
  checkpoint:
    description: Return to your checkpoint.
    aliases: [ cp ]
    usage: /checkpoint
    default: false
    permission: pkcp.checkpoint
    permission-message: You do not have permission to use this command!
  checkpointdelete:
    description: Delete a checkpoint from a player.
    aliases: [ cpd, cpdelete ]
    usage: /checkpointdelete <player> <map>
    default: false
    permission: pkcp.checkpointdelete
    permission-message: You do not have permission to use this command!
  sendtomap:
    description: Send a player to a specific map.
    aliases: [ stm ]
    usage: /sendtomap <player> <map>
    default: false
    permission: pkcp.sendtomap
    permission-message: You do not have permission to use this command!
  sendtomapworld:
    description: Send a player to a specific map world.
    aliases: [ stmw ]
    usage: /sendtomapworld <player> <map>
    default: false
    permission: pkcp.sendtomapworld
    permission-message: You do not have permission to use this command!
  savecheckpoint:
    description: Save a checkpoint right at the player's spot.
    aliases: [ savecp, scp ]
    usage: /savecheckpoint
    default: false
    permission: pkcp.savecheckpoint
    permission-message: You do not have permission to use this command!
  saves:
  nv:
    aliases: [ nightvision, nvn, vision ]
  selfmsg:
    aliases: [ sm ]
  save:
  psreload:
  fakeup:
  pingtp:
  sayall:
  forcesay:
  chungus:
  resetsaves:
  checksaves:
  pex:
  togglenotify:
  hide:
  hideall:
  showall:
  show:
  otphere:
  otp:
  maps:
  mapsreload:
  menu:
  complete:
  addcompletions:
  giveunlocks:
  checkcompletions:
permissions:
  pkprac.practice:
    description: Allows the use of the /practice and /unpractice commands.
    default: op
  pkprac.reload:
    description: Allows the use of the /pkpracreload command. (You shouldn't give this out to all players)
    default: op
  pkcp.checkpoint:
    description: Allows the use of the command /checkpoint (true by default)
    default: true
  pkcp.sendto:
    description: Allows the use of the command /sendto
    default: op
  pkcp.checkpointdelete:
    description: Allows the use of the command /checkpoint delete
    default: op
  pkcp.savecheckpoint:
    description: Allows the use of the command /savecheckpoint
    default: op

