name: LCCore
version: '${project.version}'
main: de.legoshi.lccore.Linkcraft
authors: [Leg0shi_, dklink750]
description: Core Plugin for Linkcraft
api-version: 1.8
loadbefore:
  - Essentials
softdepend:
  - DiscordSRV
  - LuckPerms
  - DeluxeTags
  - TAB
  - PlaceholderAPI
commands:
  ld:
    permission: lc.lockdown
  ldmsg:
    permission: lc.lockdownmsg
  saves:
  nv:
    aliases: [ nightvision, nvn, vision ]
  save:
  pingtp:
  chungus:
  resetsaves:
  checksaves:
  pex:
  hide:
  hideall:
  showall:
  show:
  giveunlocks:
permissions:
  pkprac.practice:
    description: Allows the use of the /practice and /unpractice commands.
    default: op
  pkprac.reload:
    description: Allows the use of the /pkpracreload command. (You shouldn't give this out to all players)
    default: op
  pkcp.checkpoint:
    description: Allows the use of the command /checkpoint (true by default)
    default: true
  pkcp.sendto:
    description: Allows the use of the command /sendto
    default: op
  pkcp.checkpointdelete:
    description: Allows the use of the command /checkpoint delete
    default: op
  pkcp.savecheckpoint:
    description: Allows the use of the command /savecheckpoint
    default: op

