name: LCCore
version: '${project.version}'
main: de.legoshi.lccore.Linkcraft
authors: [Leg0shi_, dklink750]
description: Practice Plugin for Linkcraft
api-version: 1.8
commands:
  practice:
    aliases: [prac]
    permission: pkprac.practice
  unpractice:
    aliases: [unprac]
    permission: pkprac.practice
  pkpracreload:
    permission: pkprac.reload
  saves:
  stats:
    aliases: [ stat, statistic, statistics ]
  save:
  psreload:
  fakeup:
  pingtp:
  gg:
  gl:
  rip:
  fail:
  eggs:
  ham:
  sayall:
  forcesay:
  chungus:
  ggall:
  glall:
  ripall:
  failall:
  eggsall:
  hamall:
  resetsaves:
  checksaves:
  chatcolor:
  chatformat:
  pex:
  togglenotify:
  hide:
  hideall:
  showall:
  show:
permissions:
  pkprac.practice:
    description: Allows the use of the /practice and /unpractice commands.
    default: op
  pkprac.reload:
    description: Allows the use of the /pkpracreload command. (You shouldn't give this out to all players)
    default: op

